export const VIEW_MODAL_ACTION = {
    OPEN: "VIEW_MODAL_OPEN",
    LOAD: "VIEW_MODAL_INFO_LOAD",
    CLOSE: "VIEW_MODAL_CLOSE"
};

export const EDIT_MODAL_ACTION = {
    OPEN: "EDIT_MODAL_OPEN",
    LOAD: "EDIT_MODAL_INFO_LOAD",
    CLOSE: "EDIT_MODAL_CLOSE"
};